In [8]:
library("AzureML")
ws <- workspace()
dat <- download.datasets(ws, "autos.csv")

In [10]:
str(dat)

'data.frame':	216 obs. of  26 variables:
 $ symboling        : int  3 3 1 2 2 2 1 1 1 0 ...
 $ normalized.losses: int  NA NA NA 164 164 NA 158 NA 158 NA ...
 $ make.id          : int  1 1 1 2 2 2 2 2 2 2 ...
 $ fuel.type        : chr  "gas" "gas" "gas" "gas" ...
 $ aspiration       : chr  "std" "std" "std" "std" ...
 $ num.of.doors     : chr  "two" "two" "two" "four" ...
 $ body.style       : chr  "convertible" "convertible" "hatchback" "sedan" ...
 $ drive.wheels     : chr  "rwd" "rwd" "rwd" "fwd" ...
 $ engine.location  : chr  "front" "front" "front" "front" ...
 $ wheel.base       : num  88.6 88.6 94.5 99.8 99.4 ...
 $ length           : num  169 169 171 177 177 ...
 $ width            : num  64.1 64.1 65.5 66.2 66.4 66.3 71.4 71.4 71.4 67.9 ...
 $ height           : num  48.8 48.8 52.4 54.3 54.3 53.1 55.7 55.7 55.9 52 ...
 $ curb.weight      : int  2548 2548 2823 2337 2824 2507 2844 2954 3086 3053 ...
 $ engine.type      : chr  "dohc" "dohc" "ohcv" "ohc" ...
 $ num.of.cylinders : chr  "four" "four" "six" "four" ...
 $ engine.size      : int  130 130 152 109 136 136 136 136 131 131 ...
 $ fuel.system      : chr  "mpfi" "mpfi" "mpfi" "mpfi" ...
 $ bore             : num  3.47 3.47 2.68 3.19 3.19 3.19 3.19 3.19 3.13 3.13 ...
 $ stroke           : num  2.68 2.68 3.47 3.4 3.4 3.4 3.4 3.4 3.4 3.4 ...
 $ compression.ratio: num  9 9 9 10 8 8.5 8.5 8.5 8.3 7 ...
 $ horsepower       : int  111 111 154 102 115 110 110 110 140 160 ...
 $ peak.rpm         : int  5000 5000 5000 5500 5500 5500 5500 5500 5500 5500 ...
 $ city.mpg         : int  21 21 19 24 18 19 19 19 17 16 ...
 $ highway.mpg      : int  27 27 26 30 22 25 25 25 20 22 ...
 $ price            : int  13495 16500 16500 13950 17450 15250 17710 18920 23875 NA ...

In [9]:
summary(dat)

   symboling       normalized.losses    make.id       fuel.type
 Min.   :-2.0000   Min.   : 65.0     Min.   : 1.00   Length:216
 1st Qu.: 0.0000   1st Qu.: 94.0     1st Qu.: 9.00   Class :character
 Median : 1.0000   Median :110.0     Median :14.00   Mode  :character
 Mean   : 0.7269   Mean   :120.1     Mean   :13.64
 3rd Qu.: 2.0000   3rd Qu.:148.0     3rd Qu.:20.00
 Max.   : 3.0000   Max.   :256.0     Max.   :22.00
                   NA's   :41
  aspiration        num.of.doors        body.style        drive.wheels
 Length:216         Length:216         Length:216         Length:216
 Class :character   Class :character   Class :character   Class :character
 Mode  :character   Mode  :character   Mode  :character   Mode  :character




 engine.location      wheel.base         length          width
 Length:216         Min.   : 86.60   Min.   :141.1   Min.   :60.30
 Class :character   1st Qu.: 94.50   1st Qu.:167.2   1st Qu.:64.20
 Mode  :character   Median : 97.20   Median :173.4   Median :65.55
                    Mean   : 99.15   Mean   :174.8   Mean   :66.01
                    3rd Qu.:103.30   3rd Qu.:186.6   3rd Qu.:67.20
                    Max.   :120.90   Max.   :208.1   Max.   :72.30

     height       curb.weight   engine.type        num.of.cylinders
 Min.   :47.80   Min.   :1488   Length:216         Length:216
 1st Qu.:52.00   1st Qu.:2191   Class :character   Class :character
 Median :54.10   Median :2459   Mode  :character   Mode  :character
 Mean   :53.85   Mean   :2580
 3rd Qu.:55.70   3rd Qu.:3012
 Max.   :59.80   Max.   :4066

  engine.size    fuel.system             bore           stroke
 Min.   : 61.0   Length:216         Min.   :2.540   Min.   :2.070
 1st Qu.: 98.0   Class :character   1st Qu.:3.150   1st Qu.:3.110
 Median :120.0   Mode  :character   Median :3.330   Median :3.270
 Mean   :127.7                      Mean   :3.347   Mean   :3.250
 3rd Qu.:141.0                      3rd Qu.:3.620   3rd Qu.:3.402
 Max.   :326.0                      Max.   :3.940   Max.   :4.170
                                    NA's   :4       NA's   :4
 compression.ratio   horsepower       peak.rpm       city.mpg
 Min.   : 7.00     Min.   : 48.0   Min.   :4150   Min.   :13.00
 1st Qu.: 8.60     1st Qu.: 70.0   1st Qu.:4800   1st Qu.:19.00
 Median : 9.00     Median : 97.0   Median :5200   Median :24.00
 Mean   :10.15     Mean   :105.5   Mean   :5134   Mean   :25.01
 3rd Qu.: 9.40     3rd Qu.:119.0   3rd Qu.:5500   3rd Qu.:30.00
 Max.   :23.00     Max.   :288.0   Max.   :6600   Max.   :49.00
                   NA's   :2       NA's   :2
  highway.mpg       price
 Min.   :16.0   Min.   : 5118
 1st Qu.:25.0   1st Qu.: 7871
 Median :30.0   Median :10922
 Mean   :30.5   Mean   :13459
 3rd Qu.:34.0   3rd Qu.:16646
 Max.   :54.0   Max.   :45400
                NA's   :4

In [11]:
require(dplyr)
df = filter(dat, fuel.type == "gas")
df

Loading required package: dplyr

Attaching package: 'dplyr'

The following object is masked from 'package:stats':

    filter

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

    symboling normalized.losses make.id fuel.type aspiration num.of.doors
1    3         NA               1       gas       std        two
2    3         NA               1       gas       std        two
3    1         NA               1       gas       std        two
4    2        164               2       gas       std        four
5    2        164               2       gas       std        four
6    2         NA               2       gas       std        two
7    1        158               2       gas       std        four
8    1         NA               2       gas       std        four
9    1        158               2       gas       turbo      four
10   0         NA               2       gas       turbo      two
11   2        192               3       gas       std        two
12   0        192               3       gas       std        four
13   0        188               3       gas       std        two
14   0        188               3       gas       std        four
15   1         NA               3       gas       std        four
16   0         NA               3       gas       std        four
17   0         NA               3       gas       std        two
18   0         NA               3       gas       std        four
19   2        121               4       gas       std        two
20   1         98               4       gas       std        two
21   0         81               4       gas       std        four
22   1        118               5       gas       std        two
23   1        118               5       gas       std        two
24   1        118               5       gas       turbo      two
25   1        148               5       gas       std        four
26   1        148               5       gas       std        four
27   1        148               5       gas       std        four
28   1        148               5       gas       turbo
29  -1        110               5       gas       std        four
30   3        145               5       gas       turbo      two
... ...       ...               ...     ...       ...        ...
166 -1         90               20      gas       std        four
167 -1         NA               20      gas       std        four
168  2        122               21      gas       std        two
169  2         94               21      gas       std        four
170  2         94               21      gas       std        four
171  2         94               21      gas       std        four
172  3         NA               21      gas       std        two
173  3        256               21      gas       std        two
174  0         NA               21      gas       std        four
175  0         NA               21      gas       std        four
176 -2        103               22      gas       std        four
177 -1         74               22      gas       std        four
178 -2        103               22      gas       std        four
179 -1         74               22      gas       std        four
180 -2        103               22      gas       turbo      four
181 -1         74               22      gas       turbo      four
182 -1         95               22      gas       std        four
183 -1         95               22      gas       turbo      four
184 -1         95               22      gas       std        four
185 -1         95               22      gas       turbo      four
186 -2        103               22      gas       std        four
187 -1         74               22      gas       std        four
188 -2        103               22      gas       std        four
189 -1         74               22      gas       std        four
190 -2        103               22      gas       turbo      four
191 -1         74               22      gas       turbo      four
192 -1         95               22      gas       std        four
193 -1         95               22      gas       turbo      four
194 -1         95               22      gas       std        four
195 -1         95               22      gas       turbo      four
    body.style  drive.wheels engine.location wheel.base ... engine.size
1   convertible rwd          front            88.6      ... 130
2   convertible rwd          front            88.6      ... 130
3   hatchback   rwd          front            94.5      ... 152
4   sedan       fwd          front            99.8      ... 109
5   sedan       4wd          front            99.4      ... 136
6   sedan       fwd          front            99.8      ... 136
7   sedan       fwd          front           105.8      ... 136
8   wagon       fwd          front           105.8      ... 136
9   sedan       fwd          front           105.8      ... 131
10  hatchback   4wd          front            99.5      ... 131
11  sedan       rwd          front           101.2      ... 108
12  sedan       rwd          front           101.2      ... 108
13  sedan       rwd          front           101.2      ... 164
14  sedan       rwd          front           101.2      ... 164
15  sedan       rwd          front           103.5      ... 164
16  sedan       rwd          front           103.5      ... 209
17  sedan       rwd          front           103.5      ... 209
18  sedan       rwd          front           110.0      ... 209
19  hatchback   fwd          front            88.4      ...  61
20  hatchback   fwd          front            94.5      ...  90
21  sedan       fwd          front            94.5      ...  90
22  hatchback   fwd          front            93.7      ...  90
23  hatchback   fwd          front            93.7      ...  90
24  hatchback   fwd          front            93.7      ...  98
25  hatchback   fwd          front            93.7      ...  90
26  sedan       fwd          front            93.7      ...  90
27  sedan       fwd          front            93.7      ...  90
28  sedan       fwd          front            93.7      ...  98
29  wagon       fwd          front           103.3      ... 122
30  hatchback   fwd          front            95.9      ... 156
... ...         ...          ...             ...            ...
166 sedan       rwd          front           104.5      ... 171
167 wagon       rwd          front           104.5      ... 161
168 sedan       fwd          front            97.3      ... 109
169 sedan       fwd          front            97.3      ... 109
170 sedan       fwd          front            97.3      ... 109
171 sedan       fwd          front            97.3      ... 109
172 convertible fwd          front            94.5      ... 109
173 hatchback   fwd          front            94.5      ... 109
174 sedan       fwd          front           100.4      ... 136
175 wagon       fwd          front           100.4      ... 109
176 sedan       rwd          front           104.3      ... 141
177 wagon       rwd          front           104.3      ... 141
178 sedan       rwd          front           104.3      ... 141
179 wagon       rwd          front           104.3      ... 141
180 sedan       rwd          front           104.3      ... 130
181 wagon       rwd          front           104.3      ... 130
182 sedan       rwd          front           109.1      ... 141
183 sedan       rwd          front           109.1      ... 141
184 sedan       rwd          front           109.1      ... 173
185 sedan       rwd          front           109.1      ... 141
186 sedan       rwd          front           104.3      ... 141
187 wagon       rwd          front           104.3      ... 141
188 sedan       rwd          front           104.3      ... 141
189 wagon       rwd          front           104.3      ... 141
190 sedan       rwd          front           104.3      ... 130
191 wagon       rwd          front           104.3      ... 130
192 sedan       rwd          front           109.1      ... 141
193 sedan       rwd          front           109.1      ... 141
194 sedan       rwd          front           109.1      ... 173
195 sedan       rwd          front           109.1      ... 141
    fuel.system bore stroke compression.ratio horsepower peak.rpm city.mpg
1   mpfi        3.47 2.68    9.00             111        5000     21
2   mpfi        3.47 2.68    9.00             111        5000     21
3   mpfi        2.68 3.47    9.00             154        5000     19
4   mpfi        3.19 3.40   10.00             102        5500     24
5   mpfi        3.19 3.40    8.00             115        5500     18
6   mpfi        3.19 3.40    8.50             110        5500     19
7   mpfi        3.19 3.40    8.50             110        5500     19
8   mpfi        3.19 3.40    8.50             110        5500     19
9   mpfi        3.13 3.40    8.30             140        5500     17
10  mpfi        3.13 3.40    7.00             160        5500     16
11  mpfi        3.50 2.80    8.80             101        5800     23
12  mpfi        3.50 2.80    8.80             101        5800     23
13  mpfi        3.31 3.19    9.00             121        4250     21
14  mpfi        3.31 3.19    9.00             121        4250     21
15  mpfi        3.31 3.19    9.00             121        4250     20
16  mpfi        3.62 3.39    8.00             182        5400     16
17  mpfi        3.62 3.39    8.00             182        5400     16
18  mpfi        3.62 3.39    8.00             182        5400     15
19  2bbl        2.91 3.03    9.50              48        5100     47
20  2bbl        3.03 3.11    9.60              70        5400     38
21  2bbl        3.03 3.11    9.60              70        5400     38
22  2bbl        2.97 3.23    9.41              68        5500     37
23  2bbl        2.97 3.23    9.40              68        5500     31
24  mpfi        3.03 3.39    7.60             102        5500     24
25  2bbl        2.97 3.23    9.40              68        5500     31
26  2bbl        2.97 3.23    9.40              68        5500     31
27  2bbl        2.97 3.23    9.40              68        5500     31
28  mpfi        3.03 3.39    7.60             102        5500     24
29  2bbl        3.34 3.46    8.50              88        5000     24
30  mfi         3.60 3.90    7.00             145        5000     19
... ...         ...  ...    ...               ...        ...      ...
166 mpfi        3.27 3.35    9.2              156        5200     20
167 mpfi        3.27 3.35    9.2              156        5200     19
168 mpfi        3.19 3.40    9.0               85        5250     27
169 mpfi        3.19 3.40    9.0               85        5250     27
170 mpfi        3.19 3.40    9.0               85        5250     27
171 mpfi        3.19 3.40   10.0              100        5500     26
172 mpfi        3.19 3.40    8.5               90        5500     24
173 mpfi        3.19 3.40    8.5               90        5500     24
174 mpfi        3.19 3.40    8.5              110        5500     19
175 mpfi        3.19 3.40    9.0               88        5500     25
176 mpfi        3.78 3.15    9.5              114        5400     23
177 mpfi        3.78 3.15    9.5              114        5400     23
178 mpfi        3.78 3.15    9.5              114        5400     24
179 mpfi        3.78 3.15    9.5              114        5400     24
180 mpfi        3.62 3.15    7.5              162        5100     17
181 mpfi        3.62 3.15    7.5              162        5100     17
182 mpfi        3.78 3.15    9.5              114        5400     23
183 mpfi        3.78 3.15    8.7              160        5300     19
184 mpfi        3.58 2.87    8.8              134        5500     18
185 mpfi        3.78 3.15    9.5              114        5400     19
186 mpfi        3.78 3.15    9.5              114        5400     23
187 mpfi        3.78 3.15    9.5              114        5400     23
188 mpfi        3.78 3.15    9.5              114        5400     24
189 mpfi        3.78 3.15    9.5              114        5400     24
190 mpfi        3.62 3.15    7.5              162        5100     17
191 mpfi        3.62 3.15    7.5              162        5100     17
192 mpfi        3.78 3.15    9.5              114        5400     23
193 mpfi        3.78 3.15    8.7              160        5300     19
194 mpfi        3.58 2.87    8.8              134        5500     18
195 mpfi        3.78 3.15    9.5              114        5400     19
    highway.mpg price
1   27          13495
2   27          16500
3   26          16500
4   30          13950
5   22          17450
6   25          15250
7   25          17710
8   25          18920
9   20          23875
10  22             NA
11  29          16430
12  29          16925
13  28          20970
14  28          21105
15  25          24565
16  22          30760
17  22          41315
18  20          36880
19  53           5151
20  43           6295
21  43           6575
22  41           5572
23  38           6377
24  30           7957
25  38           6229
26  38           6692
27  38           7609
28  30           8558
29  30           8921
30  24          12964
... ...         ...
166 24          15690
167 24          15750
168 34           7975
169 34           8195
170 34           8495
171 32           9995
172 29          11595
173 29           9980
174 24          13295
175 31          12290
176 28          12940
177 28          13415
178 28          15985
179 28          16515
180 22          18420
181 22          18950
182 28          16845
183 25          19045
184 23          21485
185 25          22625
186 28          12940
187 28          13415
188 28          15985
189 28          16515
190 22          18420
191 22          18950
192 28          16845
193 25          19045
194 23          21485
195 25          22625

In [14]:
summary(df)

   symboling    normalized.losses    make.id       fuel.type
 Min.   :-2.0   Min.   : 65.0     Min.   : 1.00   Length:195
 1st Qu.: 0.0   1st Qu.: 95.0     1st Qu.: 8.00   Class :character
 Median : 1.0   Median :113.0     Median :13.00   Mode  :character
 Mean   : 0.8   Mean   :121.3     Mean   :13.43
 3rd Qu.: 2.0   3rd Qu.:149.0     3rd Qu.:20.00
 Max.   : 3.0   Max.   :256.0     Max.   :22.00
                NA's   :36
  aspiration        num.of.doors        body.style        drive.wheels
 Length:195         Length:195         Length:195         Length:195
 Class :character   Class :character   Class :character   Class :character
 Mode  :character   Mode  :character   Mode  :character   Mode  :character




 engine.location      wheel.base         length          width
 Length:195         Min.   : 86.60   Min.   :141.1   Min.   :60.30
 Class :character   1st Qu.: 94.50   1st Qu.:166.6   1st Qu.:64.00
 Mode  :character   Median : 96.90   Median :173.2   Median :65.50
                    Mean   : 98.56   Mean   :174.0   Mean   :65.85
                    3rd Qu.:102.40   3rd Qu.:184.1   3rd Qu.:66.90
                    Max.   :120.90   Max.   :208.1   Max.   :72.30

     height       curb.weight   engine.type        num.of.cylinders
 Min.   :47.80   Min.   :1488   Length:195         Length:195
 1st Qu.:51.80   1st Qu.:2142   Class :character   Class :character
 Median :53.90   Median :2420   Mode  :character   Mode  :character
 Mean   :53.64   Mean   :2544
 3rd Qu.:55.50   3rd Qu.:2944
 Max.   :59.80   Max.   :4066

  engine.size    fuel.system             bore           stroke
 Min.   : 61.0   Length:195         Min.   :2.540   Min.   :2.070
 1st Qu.: 98.0   Class :character   1st Qu.:3.150   1st Qu.:3.100
 Median :120.0   Mode  :character   Median :3.330   Median :3.230
 Mean   :126.8                      Mean   :3.346   Mean   :3.224
 3rd Qu.:141.0                      3rd Qu.:3.620   3rd Qu.:3.400
 Max.   :326.0                      Max.   :3.940   Max.   :4.170
                                    NA's   :4       NA's   :4
 compression.ratio   horsepower       peak.rpm       city.mpg
 Min.   : 7.000    Min.   : 48.0   Min.   :4200   Min.   :13.00
 1st Qu.: 8.500    1st Qu.: 73.0   1st Qu.:4900   1st Qu.:19.00
 Median : 9.000    Median :101.0   Median :5200   Median :24.00
 Mean   : 8.865    Mean   :107.7   Mean   :5208   Mean   :24.47
 3rd Qu.: 9.400    3rd Qu.:121.0   3rd Qu.:5500   3rd Qu.:29.00
 Max.   :11.500    Max.   :288.0   Max.   :6600   Max.   :49.00
                   NA's   :2       NA's   :2
  highway.mpg        price
 Min.   :16.00   Min.   : 5118
 1st Qu.:25.00   1st Qu.: 7756
 Median :30.00   Median :10345
 Mean   :30.08   Mean   :13163
 3rd Qu.:34.00   3rd Qu.:16502
 Max.   :54.00   Max.   :45400
                 NA's   :4

In [15]:
str(df)

'data.frame':	195 obs. of  26 variables:
 $ symboling        : int  3 3 1 2 2 2 1 1 1 0 ...
 $ normalized.losses: int  NA NA NA 164 164 NA 158 NA 158 NA ...
 $ make.id          : int  1 1 1 2 2 2 2 2 2 2 ...
 $ fuel.type        : chr  "gas" "gas" "gas" "gas" ...
 $ aspiration       : chr  "std" "std" "std" "std" ...
 $ num.of.doors     : chr  "two" "two" "two" "four" ...
 $ body.style       : chr  "convertible" "convertible" "hatchback" "sedan" ...
 $ drive.wheels     : chr  "rwd" "rwd" "rwd" "fwd" ...
 $ engine.location  : chr  "front" "front" "front" "front" ...
 $ wheel.base       : num  88.6 88.6 94.5 99.8 99.4 ...
 $ length           : num  169 169 171 177 177 ...
 $ width            : num  64.1 64.1 65.5 66.2 66.4 66.3 71.4 71.4 71.4 67.9 ...
 $ height           : num  48.8 48.8 52.4 54.3 54.3 53.1 55.7 55.7 55.9 52 ...
 $ curb.weight      : int  2548 2548 2823 2337 2824 2507 2844 2954 3086 3053 ...
 $ engine.type      : chr  "dohc" "dohc" "ohcv" "ohc" ...
 $ num.of.cylinders : chr  "four" "four" "six" "four" ...
 $ engine.size      : int  130 130 152 109 136 136 136 136 131 131 ...
 $ fuel.system      : chr  "mpfi" "mpfi" "mpfi" "mpfi" ...
 $ bore             : num  3.47 3.47 2.68 3.19 3.19 3.19 3.19 3.19 3.13 3.13 ...
 $ stroke           : num  2.68 2.68 3.47 3.4 3.4 3.4 3.4 3.4 3.4 3.4 ...
 $ compression.ratio: num  9 9 9 10 8 8.5 8.5 8.5 8.3 7 ...
 $ horsepower       : int  111 111 154 102 115 110 110 110 140 160 ...
 $ peak.rpm         : int  5000 5000 5000 5500 5500 5500 5500 5500 5500 5500 ...
 $ city.mpg         : int  21 21 19 24 18 19 19 19 17 16 ...
 $ highway.mpg      : int  27 27 26 30 22 25 25 25 20 22 ...
 $ price            : int  13495 16500 16500 13950 17450 15250 17710 18920 23875 NA ...

In [17]:
df.slice = slice(df, 1:50)

In [20]:
str(df.slice)

'data.frame':	50 obs. of  26 variables:
 $ symboling        : int  3 3 1 2 2 2 1 1 1 0 ...
 $ normalized.losses: int  NA NA NA 164 164 NA 158 NA 158 NA ...
 $ make.id          : int  1 1 1 2 2 2 2 2 2 2 ...
 $ fuel.type        : chr  "gas" "gas" "gas" "gas" ...
 $ aspiration       : chr  "std" "std" "std" "std" ...
 $ num.of.doors     : chr  "two" "two" "two" "four" ...
 $ body.style       : chr  "convertible" "convertible" "hatchback" "sedan" ...
 $ drive.wheels     : chr  "rwd" "rwd" "rwd" "fwd" ...
 $ engine.location  : chr  "front" "front" "front" "front" ...
 $ wheel.base       : num  88.6 88.6 94.5 99.8 99.4 ...
 $ length           : num  169 169 171 177 177 ...
 $ width            : num  64.1 64.1 65.5 66.2 66.4 66.3 71.4 71.4 71.4 67.9 ...
 $ height           : num  48.8 48.8 52.4 54.3 54.3 53.1 55.7 55.7 55.9 52 ...
 $ curb.weight      : int  2548 2548 2823 2337 2824 2507 2844 2954 3086 3053 ...
 $ engine.type      : chr  "dohc" "dohc" "ohcv" "ohc" ...
 $ num.of.cylinders : chr  "four" "four" "six" "four" ...
 $ engine.size      : int  130 130 152 109 136 136 136 136 131 131 ...
 $ fuel.system      : chr  "mpfi" "mpfi" "mpfi" "mpfi" ...
 $ bore             : num  3.47 3.47 2.68 3.19 3.19 3.19 3.19 3.19 3.13 3.13 ...
 $ stroke           : num  2.68 2.68 3.47 3.4 3.4 3.4 3.4 3.4 3.4 3.4 ...
 $ compression.ratio: num  9 9 9 10 8 8.5 8.5 8.5 8.3 7 ...
 $ horsepower       : int  111 111 154 102 115 110 110 110 140 160 ...
 $ peak.rpm         : int  5000 5000 5000 5500 5500 5500 5500 5500 5500 5500 ...
 $ city.mpg         : int  21 21 19 24 18 19 19 19 17 16 ...
 $ highway.mpg      : int  27 27 26 30 22 25 25 25 20 22 ...
 $ price            : int  13495 16500 16500 13950 17450 15250 17710 18920 23875 NA ...

In [21]:
df.rand = sample_frac(df.slice, 0.5)
df.rand

   symboling normalized.losses make.id fuel.type aspiration num.of.doors
19  2        121               4       gas       std        two
43  1        107               6       gas       std        two
10  0         NA               2       gas       turbo      two
37  0         78               6       gas       std        four
42  0         85               6       gas       std        four
48  0        145               8       gas       std        four
23  1        118               5       gas       std        two
1   3         NA               1       gas       std        two
18  0         NA               3       gas       std        four
15  1         NA               3       gas       std        four
46  0         NA               7       gas       std        four
4   2        164               2       gas       std        four
50  0         NA               8       gas       std        two
11  2        192               3       gas       std        two
22  1        118               5       gas       std        two
40  0         85               6       gas       std        four
34  1        101               6       gas       std        two
44  0         NA               7       gas       std        four
29 -1        110               5       gas       std        four
27  1        148               5       gas       std        four
49  0         NA               8       gas       std        four
45  1         NA               7       gas       std        two
28  1        148               5       gas       turbo
39  0        106               6       gas       std        two
17  0         NA               3       gas       std        two
   body.style  drive.wheels engine.location wheel.base ... engine.size
19 hatchback   fwd          front            88.4      ...  61
43 sedan       fwd          front            96.5      ... 110
10 hatchback   4wd          front            99.5      ... 131
37 wagon       fwd          front            96.5      ...  92
42 sedan       fwd          front            96.5      ... 110
48 sedan       rwd          front           113.0      ... 258
23 hatchback   fwd          front            93.7      ...  90
1  convertible rwd          front            88.6      ... 130
18 sedan       rwd          front           110.0      ... 209
15 sedan       rwd          front           103.5      ... 164
46 sedan       fwd          front            94.5      ...  90
4  sedan       fwd          front            99.8      ... 109
50 sedan       rwd          front           102.0      ... 326
11 sedan       rwd          front           101.2      ... 108
22 hatchback   fwd          front            93.7      ...  90
40 sedan       fwd          front            96.5      ... 110
34 hatchback   fwd          front            93.7      ...  92
44 sedan       rwd          front            94.3      ... 111
29 wagon       fwd          front           103.3      ... 122
27 sedan       fwd          front            93.7      ...  90
49 sedan       rwd          front           113.0      ... 258
45 sedan       fwd          front            94.5      ...  90
28 sedan       fwd          front            93.7      ...  98
39 hatchback   fwd          front            96.5      ... 110
17 sedan       rwd          front           103.5      ... 209
   fuel.system bore stroke compression.ratio horsepower peak.rpm city.mpg
19 2bbl        2.91 3.03    9.50              48        5100     47
43 2bbl        3.15 3.58    9.10             100        5500     25
10 mpfi        3.13 3.40    7.00             160        5500     16
37 1bbl        2.92 3.41    9.20              76        6000     30
42 mpfi        3.15 3.58    9.00             101        5800     24
48 mpfi        3.63 4.17    8.10             176        4750     15
23 2bbl        2.97 3.23    9.40              68        5500     31
1  mpfi        3.47 2.68    9.00             111        5000     21
18 mpfi        3.62 3.39    8.00             182        5400     15
15 mpfi        3.31 3.19    9.00             121        4250     20
46 2bbl        3.03 3.11    9.60              70        5400     38
4  mpfi        3.19 3.40   10.00             102        5500     24
50 mpfi        3.54 2.76   11.50             262        5000     13
11 mpfi        3.50 2.80    8.80             101        5800     23
22 2bbl        2.97 3.23    9.41              68        5500     37
40 1bbl        3.15 3.58    9.00              86        5800     27
34 1bbl        2.91 3.41    9.20              76        6000     30
44 2bbl        3.31 3.23    8.50              78        4800     24
29 2bbl        3.34 3.46    8.50              88        5000     24
27 2bbl        2.97 3.23    9.40              68        5500     31
49 mpfi        3.63 4.17    8.10             176        4750     15
45 2bbl        3.03 3.11    9.60              70        5400     38
28 mpfi        3.03 3.39    7.60             102        5500     24
39 1bbl        3.15 3.58    9.00              86        5800     27
17 mpfi        3.62 3.39    8.00             182        5400     16
   highway.mpg price
19 53           5151
43 31          10345
10 22             NA
37 34           7295
42 28          12945
48 19          32250
23 38           6377
1  27          13495
18 20          36880
15 25          24565
46 43             NA
4  30          13950
50 17          36000
11 29          16430
22 41           5572
40 33           8845
34 34           6529
44 29           6785
29 30           8921
27 38           7609
49 19          35550
45 43             NA
28 30           8558
39 33           9095
17 22          41315

In [22]:
df2 = select(dat, fuel.type, make.id, highway.mpg, city.mpg, price)
df2

    fuel.type make.id highway.mpg city.mpg price
1   gas       1       27          21       13495
2   gas       1       27          21       16500
3   gas       1       26          19       16500
4   gas       2       30          24       13950
5   gas       2       22          18       17450
6   gas       2       25          19       15250
7   gas       2       25          19       17710
8   gas       2       25          19       18920
9   gas       2       20          17       23875
10  gas       2       22          16          NA
11  gas       3       29          23       16430
12  gas       3       29          23       16925
13  gas       3       28          21       20970
14  gas       3       28          21       21105
15  gas       3       25          20       24565
16  gas       3       22          16       30760
17  gas       3       22          16       41315
18  gas       3       20          15       36880
19  gas       4       53          47        5151
20  gas       4       43          38        6295
21  gas       4       43          38        6575
22  gas       5       41          37        5572
23  gas       5       38          31        6377
24  gas       5       30          24        7957
25  gas       5       38          31        6229
26  gas       5       38          31        6692
27  gas       5       38          31        7609
28  gas       5       30          24        8558
29  gas       5       30          24        8921
30  gas       5       24          19       12964
... ...       ...     ...         ...      ...
187 gas       21      34          27        8495
188 diesel    21      42          37        9495
189 gas       21      32          26        9995
190 gas       21      29          24       11595
191 gas       21      29          24        9980
192 gas       21      24          19       13295
193 diesel    21      38          33       13845
194 gas       21      31          25       12290
195 gas       22      28          23       12940
196 gas       22      28          23       13415
197 gas       22      28          24       15985
198 gas       22      28          24       16515
199 gas       22      22          17       18420
200 gas       22      22          17       18950
201 gas       22      28          23       16845
202 gas       22      25          19       19045
203 gas       22      23          18       21485
204 diesel    22      27          26       22470
205 gas       22      25          19       22625
206 gas       22      28          23       12940
207 gas       22      28          23       13415
208 gas       22      28          24       15985
209 gas       22      28          24       16515
210 gas       22      22          17       18420
211 gas       22      22          17       18950
212 gas       22      28          23       16845
213 gas       22      25          19       19045
214 gas       22      23          18       21485
215 diesel    22      27          26       22470
216 gas       22      25          19       22625

In [23]:
summary(df2)

  fuel.type            make.id       highway.mpg      city.mpg
 Length:216         Min.   : 1.00   Min.   :16.0   Min.   :13.00
 Class :character   1st Qu.: 9.00   1st Qu.:25.0   1st Qu.:19.00
 Mode  :character   Median :14.00   Median :30.0   Median :24.00
                    Mean   :13.64   Mean   :30.5   Mean   :25.01
                    3rd Qu.:20.00   3rd Qu.:34.0   3rd Qu.:30.00
                    Max.   :22.00   Max.   :54.0   Max.   :49.00

     price
 Min.   : 5118
 1st Qu.: 7871
 Median :10922
 Mean   :13459
 3rd Qu.:16646
 Max.   :45400
 NA's   :4

In [24]:
str(df2)

'data.frame':	216 obs. of  5 variables:
 $ fuel.type  : chr  "gas" "gas" "gas" "gas" ...
 $ make.id    : int  1 1 1 2 2 2 2 2 2 2 ...
 $ highway.mpg: int  27 27 26 30 22 25 25 25 20 22 ...
 $ city.mpg   : int  21 21 19 24 18 19 19 19 17 16 ...
 $ price      : int  13495 16500 16500 13950 17450 15250 17710 18920 23875 NA ...

In [25]:
df2.slice = slice(df2, 1:50)
df2.slice

   fuel.type make.id highway.mpg city.mpg price
1  gas       1       27          21       13495
2  gas       1       27          21       16500
3  gas       1       26          19       16500
4  gas       2       30          24       13950
5  gas       2       22          18       17450
6  gas       2       25          19       15250
7  gas       2       25          19       17710
8  gas       2       25          19       18920
9  gas       2       20          17       23875
10 gas       2       22          16          NA
11 gas       3       29          23       16430
12 gas       3       29          23       16925
13 gas       3       28          21       20970
14 gas       3       28          21       21105
15 gas       3       25          20       24565
16 gas       3       22          16       30760
17 gas       3       22          16       41315
18 gas       3       20          15       36880
19 gas       4       53          47        5151
20 gas       4       43          38        6295
21 gas       4       43          38        6575
22 gas       5       41          37        5572
23 gas       5       38          31        6377
24 gas       5       30          24        7957
25 gas       5       38          31        6229
26 gas       5       38          31        6692
27 gas       5       38          31        7609
28 gas       5       30          24        8558
29 gas       5       30          24        8921
30 gas       5       24          19       12964
31 gas       6       54          49        6479
32 gas       6       38          31        6855
33 gas       6       42          38        5399
34 gas       6       34          30        6529
35 gas       6       34          30        7129
36 gas       6       34          30        7295
37 gas       6       34          30        7295
38 gas       6       33          27        7895
39 gas       6       33          27        9095
40 gas       6       33          27        8845
41 gas       6       33          27       10295
42 gas       6       28          24       12945
43 gas       6       31          25       10345
44 gas       7       29          24        6785
45 gas       7       43          38          NA
46 gas       7       43          38          NA
47 gas       7       29          24       11048
48 gas       8       19          15       32250
49 gas       8       19          15       35550
50 gas       8       17          13       36000

In [27]:
df2.rand = sample_frac(df2, .10)
df2.rand

    fuel.type make.id highway.mpg city.mpg price
202 gas       22      25          19       19045
165 gas       20      34          29        8238
210 gas       22      22          17       18420
57  gas        9      23          17       11845
68  diesel    10      25          22       25552
43  gas        6      31          25       10345
178 gas       20      32          27       11248
88  gas       12      30          23        9279
107 gas       13      25          19       18399
184 gas       21      34          27        7975
3   gas        1      26          19       16500
61  gas        9      32          26        8495
155 gas       20      32          27        7898
42  gas        6      28          24       12945
26  gas        5      38          31        6692
81  gas       12      30          23        9959
58  gas        9      23          17       13645
53  gas        9      38          31        6795
150 gas       19      23          23       11694
121 gas       15      38          31        6229
133 gas       18      28          21       11850
204 diesel    22      27          26       22470

In [28]:
str(df2.rand)

'data.frame':	22 obs. of  5 variables:
 $ fuel.type  : chr  "gas" "gas" "gas" "gas" ...
 $ make.id    : int  22 20 22 9 10 6 20 12 13 21 ...
 $ highway.mpg: int  25 34 22 23 25 31 32 30 25 34 ...
 $ city.mpg   : int  19 29 17 17 22 25 27 23 19 27 ...
 $ price      : int  19045 8238 18420 11845 25552 10345 11248 9279 18399 7975 ...

In [29]:
summary(df2.rand)

  fuel.type            make.id       highway.mpg       city.mpg
 Length:22          Min.   : 1.00   Min.   :22.00   Min.   :17.00
 Class :character   1st Qu.: 9.00   1st Qu.:25.00   1st Qu.:19.50
 Mode  :character   Median :12.50   Median :29.00   Median :23.50
                    Mean   :13.64   Mean   :29.27   Mean   :23.82
                    3rd Qu.:20.00   3rd Qu.:32.00   3rd Qu.:27.00
                    Max.   :22.00   Max.   :38.00   Max.   :31.00
     price
 Min.   : 6229
 1st Qu.: 8302
 Median :11471
 Mean   :12524
 3rd Qu.:15786
 Max.   :25552

In [30]:
df2.rand

    fuel.type make.id highway.mpg city.mpg price
202 gas       22      25          19       19045
165 gas       20      34          29        8238
210 gas       22      22          17       18420
57  gas        9      23          17       11845
68  diesel    10      25          22       25552
43  gas        6      31          25       10345
178 gas       20      32          27       11248
88  gas       12      30          23        9279
107 gas       13      25          19       18399
184 gas       21      34          27        7975
3   gas        1      26          19       16500
61  gas        9      32          26        8495
155 gas       20      32          27        7898
42  gas        6      28          24       12945
26  gas        5      38          31        6692
81  gas       12      30          23        9959
58  gas        9      23          17       13645
53  gas        9      38          31        6795
150 gas       19      23          23       11694
121 gas       15      38          31        6229
133 gas       18      28          21       11850
204 diesel    22      27          26       22470

In [44]:
df2.arrange = arrange(df2.rand, fuel.type, price)
df2.arrange

   fuel.type make.id highway.mpg city.mpg price
1  diesel    22      27          26       22470
2  diesel    10      25          22       25552
3  gas       15      38          31        6229
4  gas        5      38          31        6692
5  gas        9      38          31        6795
6  gas       20      32          27        7898
7  gas       21      34          27        7975
8  gas       20      34          29        8238
9  gas        9      32          26        8495
10 gas       12      30          23        9279
11 gas       12      30          23        9959
12 gas        6      31          25       10345
13 gas       20      32          27       11248
14 gas       19      23          23       11694
15 gas        9      23          17       11845
16 gas       18      28          21       11850
17 gas        6      28          24       12945
18 gas        9      23          17       13645
19 gas        1      26          19       16500
20 gas       13      25          19       18399
21 gas       22      22          17       18420
22 gas       22      25          19       19045

In [45]:
summary(dat)

   symboling       normalized.losses    make.id       fuel.type
 Min.   :-2.0000   Min.   : 65.0     Min.   : 1.00   Length:216
 1st Qu.: 0.0000   1st Qu.: 94.0     1st Qu.: 9.00   Class :character
 Median : 1.0000   Median :110.0     Median :14.00   Mode  :character
 Mean   : 0.7269   Mean   :120.1     Mean   :13.64
 3rd Qu.: 2.0000   3rd Qu.:148.0     3rd Qu.:20.00
 Max.   : 3.0000   Max.   :256.0     Max.   :22.00
                   NA's   :41
  aspiration        num.of.doors        body.style        drive.wheels
 Length:216         Length:216         Length:216         Length:216
 Class :character   Class :character   Class :character   Class :character
 Mode  :character   Mode  :character   Mode  :character   Mode  :character




 engine.location      wheel.base         length          width
 Length:216         Min.   : 86.60   Min.   :141.1   Min.   :60.30
 Class :character   1st Qu.: 94.50   1st Qu.:167.2   1st Qu.:64.20
 Mode  :character   Median : 97.20   Median :173.4   Median :65.55
                    Mean   : 99.15   Mean   :174.8   Mean   :66.01
                    3rd Qu.:103.30   3rd Qu.:186.6   3rd Qu.:67.20
                    Max.   :120.90   Max.   :208.1   Max.   :72.30

     height       curb.weight   engine.type        num.of.cylinders
 Min.   :47.80   Min.   :1488   Length:216         Length:216
 1st Qu.:52.00   1st Qu.:2191   Class :character   Class :character
 Median :54.10   Median :2459   Mode  :character   Mode  :character
 Mean   :53.85   Mean   :2580
 3rd Qu.:55.70   3rd Qu.:3012
 Max.   :59.80   Max.   :4066

  engine.size    fuel.system             bore           stroke
 Min.   : 61.0   Length:216         Min.   :2.540   Min.   :2.070
 1st Qu.: 98.0   Class :character   1st Qu.:3.150   1st Qu.:3.110
 Median :120.0   Mode  :character   Median :3.330   Median :3.270
 Mean   :127.7                      Mean   :3.347   Mean   :3.250
 3rd Qu.:141.0                      3rd Qu.:3.620   3rd Qu.:3.402
 Max.   :326.0                      Max.   :3.940   Max.   :4.170
                                    NA's   :4       NA's   :4
 compression.ratio   horsepower       peak.rpm       city.mpg
 Min.   : 7.00     Min.   : 48.0   Min.   :4150   Min.   :13.00
 1st Qu.: 8.60     1st Qu.: 70.0   1st Qu.:4800   1st Qu.:19.00
 Median : 9.00     Median : 97.0   Median :5200   Median :24.00
 Mean   :10.15     Mean   :105.5   Mean   :5134   Mean   :25.01
 3rd Qu.: 9.40     3rd Qu.:119.0   3rd Qu.:5500   3rd Qu.:30.00
 Max.   :23.00     Max.   :288.0   Max.   :6600   Max.   :49.00
                   NA's   :2       NA's   :2
  highway.mpg       price
 Min.   :16.0   Min.   : 5118
 1st Qu.:25.0   1st Qu.: 7871
 Median :30.0   Median :10922
 Mean   :30.5   Mean   :13459
 3rd Qu.:34.0   3rd Qu.:16646
 Max.   :54.0   Max.   :45400
                NA's   :4

In [46]:
str(dat)

'data.frame':	216 obs. of  26 variables:
 $ symboling        : int  3 3 1 2 2 2 1 1 1 0 ...
 $ normalized.losses: int  NA NA NA 164 164 NA 158 NA 158 NA ...
 $ make.id          : int  1 1 1 2 2 2 2 2 2 2 ...
 $ fuel.type        : chr  "gas" "gas" "gas" "gas" ...
 $ aspiration       : chr  "std" "std" "std" "std" ...
 $ num.of.doors     : chr  "two" "two" "two" "four" ...
 $ body.style       : chr  "convertible" "convertible" "hatchback" "sedan" ...
 $ drive.wheels     : chr  "rwd" "rwd" "rwd" "fwd" ...
 $ engine.location  : chr  "front" "front" "front" "front" ...
 $ wheel.base       : num  88.6 88.6 94.5 99.8 99.4 ...
 $ length           : num  169 169 171 177 177 ...
 $ width            : num  64.1 64.1 65.5 66.2 66.4 66.3 71.4 71.4 71.4 67.9 ...
 $ height           : num  48.8 48.8 52.4 54.3 54.3 53.1 55.7 55.7 55.9 52 ...
 $ curb.weight      : int  2548 2548 2823 2337 2824 2507 2844 2954 3086 3053 ...
 $ engine.type      : chr  "dohc" "dohc" "ohcv" "ohc" ...
 $ num.of.cylinders : chr  "four" "four" "six" "four" ...
 $ engine.size      : int  130 130 152 109 136 136 136 136 131 131 ...
 $ fuel.system      : chr  "mpfi" "mpfi" "mpfi" "mpfi" ...
 $ bore             : num  3.47 3.47 2.68 3.19 3.19 3.19 3.19 3.19 3.13 3.13 ...
 $ stroke           : num  2.68 2.68 3.47 3.4 3.4 3.4 3.4 3.4 3.4 3.4 ...
 $ compression.ratio: num  9 9 9 10 8 8.5 8.5 8.5 8.3 7 ...
 $ horsepower       : int  111 111 154 102 115 110 110 110 140 160 ...
 $ peak.rpm         : int  5000 5000 5000 5500 5500 5500 5500 5500 5500 5500 ...
 $ city.mpg         : int  21 21 19 24 18 19 19 19 17 16 ...
 $ highway.mpg      : int  27 27 26 30 22 25 25 25 20 22 ...
 $ price            : int  13495 16500 16500 13950 17450 15250 17710 18920 23875 NA ...

In [55]:
df4 = mutate(dat, curb.weight.kg = curb.weight / 2.205, weight.horsepower = curb.weight / horsepower)
select(df4, curb.weight, curb.weight.kg, weight.horsepower)

    curb.weight curb.weight.kg weight.horsepower
1   2548        1155.5556      22.95495
2   2548        1155.5556      22.95495
3   2823        1280.2721      18.33117
4   2337        1059.8639      22.91176
5   2824        1280.7256      24.55652
6   2507        1136.9615      22.79091
7   2844        1289.7959      25.85455
8   2954        1339.6825      26.85455
9   3086        1399.5465      22.04286
10  3053        1384.5805      19.08125
11  2395        1086.1678      23.71287
12  2395        1086.1678      23.71287
13  2710        1229.0249      22.39669
14  2765        1253.9683      22.85124
15  3055        1385.4875      25.24793
16  3230        1464.8526      17.74725
17  3380        1532.8798      18.57143
18  3505        1589.5692      19.25824
19  1488         674.8299      31.00000
20  1874         849.8866      26.77143
21  1909         865.7596      27.27143
22  1876         850.7937      27.58824
23  1876         850.7937      27.58824
24  2128         965.0794      20.86275
25  1967         892.0635      28.92647
26  1989         902.0408      29.25000
27  1989         902.0408      29.25000
28  2191         993.6508      21.48039
29  2535        1149.6599      28.80682
30  2811        1274.8299      19.38621
... ...         ...            ...
187 2275        1031.746       26.76471
188 2319        1051.701       34.10294
189 2300        1043.084       23.00000
190 2254        1022.222       25.04444
191 2221        1007.256       24.67778
192 2661        1206.803       24.19091
193 2579        1169.615       37.92647
194 2563        1162.358       29.12500
195 2912        1320.635       25.54386
196 3034        1375.964       26.61404
197 2935        1331.066       25.74561
198 3042        1379.592       26.68421
199 3045        1380.952       18.79630
200 3157        1431.746       19.48765
201 2952        1338.776       25.89474
202 3049        1382.766       19.05625
203 3012        1365.986       22.47761
204 3217        1458.957       30.34906
205 3062        1388.662       26.85965
206 2912        1320.635       25.54386
207 3034        1375.964       26.61404
208 2935        1331.066       25.74561
209 3042        1379.592       26.68421
210 3045        1380.952       18.79630
211 3157        1431.746       19.48765
212 2952        1338.776       25.89474
213 3049        1382.766       19.05625
214 3012        1365.986       22.47761
215 3217        1458.957       30.34906
216 3062        1388.662       26.85965

In [57]:
summarise(df4, mean.curb.weight = mean(curb.weight, na.rm = TRUE), sd.curb.weight = sd(curb.weight, na.rm = TRUE), max.curb.weight = max(curb.weight), min.curb.weight = min(curb.weight))

  mean.curb.weight sd.curb.weight max.curb.weight min.curb.weight
1 2580.13          518.5688       4066            1488

In [58]:
str(dat)

'data.frame':	216 obs. of  26 variables:
 $ symboling        : int  3 3 1 2 2 2 1 1 1 0 ...
 $ normalized.losses: int  NA NA NA 164 164 NA 158 NA 158 NA ...
 $ make.id          : int  1 1 1 2 2 2 2 2 2 2 ...
 $ fuel.type        : chr  "gas" "gas" "gas" "gas" ...
 $ aspiration       : chr  "std" "std" "std" "std" ...
 $ num.of.doors     : chr  "two" "two" "two" "four" ...
 $ body.style       : chr  "convertible" "convertible" "hatchback" "sedan" ...
 $ drive.wheels     : chr  "rwd" "rwd" "rwd" "fwd" ...
 $ engine.location  : chr  "front" "front" "front" "front" ...
 $ wheel.base       : num  88.6 88.6 94.5 99.8 99.4 ...
 $ length           : num  169 169 171 177 177 ...
 $ width            : num  64.1 64.1 65.5 66.2 66.4 66.3 71.4 71.4 71.4 67.9 ...
 $ height           : num  48.8 48.8 52.4 54.3 54.3 53.1 55.7 55.7 55.9 52 ...
 $ curb.weight      : int  2548 2548 2823 2337 2824 2507 2844 2954 3086 3053 ...
 $ engine.type      : chr  "dohc" "dohc" "ohcv" "ohc" ...
 $ num.of.cylinders : chr  "four" "four" "six" "four" ...
 $ engine.size      : int  130 130 152 109 136 136 136 136 131 131 ...
 $ fuel.system      : chr  "mpfi" "mpfi" "mpfi" "mpfi" ...
 $ bore             : num  3.47 3.47 2.68 3.19 3.19 3.19 3.19 3.19 3.13 3.13 ...
 $ stroke           : num  2.68 2.68 3.47 3.4 3.4 3.4 3.4 3.4 3.4 3.4 ...
 $ compression.ratio: num  9 9 9 10 8 8.5 8.5 8.5 8.3 7 ...
 $ horsepower       : int  111 111 154 102 115 110 110 110 140 160 ...
 $ peak.rpm         : int  5000 5000 5000 5500 5500 5500 5500 5500 5500 5500 ...
 $ city.mpg         : int  21 21 19 24 18 19 19 19 17 16 ...
 $ highway.mpg      : int  27 27 26 30 22 25 25 25 20 22 ...
 $ price            : int  13495 16500 16500 13950 17450 15250 17710 18920 23875 NA ...

In [60]:
count (dat, body.style, num.of.cylinders)

   body.style  num.of.cylinders n
1  convertible eight             1
2  convertible four              4
3  convertible six               1
4  hardtop     eight             1
5  hardtop     five              1
6  hardtop     four              4
7  hardtop     six               2
8  hatchback   eight             1
9  hatchback   five              1
10 hatchback   four             57
11 hatchback   six               6
12 hatchback   three             1
13 hatchback   two               4
14 sedan       eight             2
15 sedan       five              7
16 sedan       four             79
17 sedan       six              15
18 sedan       twelve            1
19 wagon       five              2
20 wagon       four             24
21 wagon       six               2

In [66]:
df.chain = dat %>%
filter (fuel.type == 'gas') %>%
select (price, fuel.type, city.mpg, highway.mpg) %>%
arrange (highway.mpg, price)
df.chain

    price fuel.type city.mpg highway.mpg
1   40960 gas       14       16
2   45400 gas       14       16
3   36000 gas       13       17
4   34184 gas       16       18
5   35056 gas       16       18
6   32250 gas       15       19
7   35550 gas       15       19
8   23875 gas       17       20
9   36880 gas       15       20
10  13499 gas       17       22
11  14399 gas       17       22
12  17450 gas       18       22
13  18420 gas       17       22
14  18420 gas       17       22
15  18950 gas       17       22
16  18950 gas       17       22
17  30760 gas       16       22
18  41315 gas       16       22
19     NA gas       16       22
20  10945 gas       17       23
21  11694 gas       23       23
22  11845 gas       17       23
23  13645 gas       17       23
24  15645 gas       16       23
25  19699 gas       17       23
26  21485 gas       18       23
27  21485 gas       18       23
28  11900 gas       19       24
29  12440 gas       19       24
30  12629 gas       19       24
... ...   ...       ...      ...
166 7999  gas       31       37
167 8249  gas       31       37
168 6095  gas       31       38
169 6189  gas       31       38
170 6229  gas       31       38
171 6229  gas       31       38
172 6338  gas       31       38
173 6377  gas       31       38
174 6488  gas       31       38
175 6669  gas       31       38
176 6692  gas       31       38
177 6692  gas       31       38
178 6695  gas       31       38
179 6795  gas       31       38
180 6855  gas       31       38
181 7395  gas       31       38
182 7609  gas       31       38
183 7609  gas       31       38
184 5348  gas       35       39
185 5389  gas       37       41
186 5572  gas       37       41
187 5572  gas       37       41
188 5399  gas       38       42
189 6295  gas       38       43
190 6575  gas       38       43
191   NA  gas       38       43
192   NA  gas       38       43
193 7738  gas       38       47
194 5151  gas       47       53
195 6479  gas       49       54

In [67]:
str(df.chain)

'data.frame':	195 obs. of  4 variables:
 $ price      : int  40960 45400 36000 34184 35056 32250 35550 23875 36880 13499 ...
 $ fuel.type  : chr  "gas" "gas" "gas" "gas" ...
 $ city.mpg   : int  14 14 13 16 16 15 15 17 15 17 ...
 $ highway.mpg: int  16 16 17 18 18 19 19 20 20 22 ...

In [93]:
df.group = dat %>% group_by(fuel.type) %>%
summarise (count = n(), mean.price = mean(price, na.rm = TRUE), sd.price = sd(price, na.rm = TRUE), min.price = min(price, na.rm = TRUE), max.price = max(price, na.rm = TRUE))
df.group

  fuel.type count mean.price sd.price min.price max.price
1 diesel     21   16153.95   7700.569 7099      31600
2 gas       195   13162.80   7824.296 5118      45400

In [91]:
summarise(dat, min.price = min(price, na.rm = TRUE))

  min.price
1 5118

In [99]:
df5 = dat %>% filter(fuel.type == "gas") %>% group_by(city.mpg) %>%
summarise (count = n(), mean.weight = mean(curb.weight), sd.weight = sd(curb.weight, na.rm = TRUE), min.weight = min(curb.weight), max.weight = max(curb.weight)) 
df5

   city.mpg count mean.weight sd.weight min.weight max.weight
1  13        1    3950.000           NA 3950       3950
2  14        2    3807.500    130.81475 3715       3900
3  15        3    3879.000    323.89350 3505       4066
4  16        6    3264.667    457.52450 2500       3740
5  17       15    2922.867    330.31540 2380       3366
6  18        4    2994.500    126.54775 2824       3130
7  19       29    2946.724    177.05243 2507       3285
8  20        3    3054.000     77.50484 2976       3131
9  21        8    2673.625     84.65887 2548       2765
10 23       15    2658.067    272.31034 2370       3034
11 24       24    2535.583    295.33134 2128       3042
12 25        6    2401.500     97.43049 2293       2563
13 26       11    2325.455     92.72148 2120       2425
14 27       14    2372.071    225.50506 2209       3110
15 28        4    2185.500     75.37241 2122       2290
16 29        3    2233.000     82.41966 2169       2326
17 30        7    2001.429     78.25143 1890       2109
18 31       27    1984.593     92.00763 1819       2280
19 32        1    2145.000           NA 2145       2145
20 35        1    1985.000           NA 1985       1985
21 37        3    1904.000     24.24871 1876       1918
22 38        6    1916.167     91.16012 1837       2094
23 47        1    1488.000           NA 1488       1488
24 49        1    1713.000           NA 1713       1713

In [102]:
df5.slice = slice(df5, 1:10)
df5.slice

   city.mpg count mean.weight sd.weight min.weight max.weight
1  13        1    3950.000           NA 3950       3950
2  14        2    3807.500    130.81475 3715       3900
3  15        3    3879.000    323.89350 3505       4066
4  16        6    3264.667    457.52450 2500       3740
5  17       15    2922.867    330.31540 2380       3366
6  18        4    2994.500    126.54775 2824       3130
7  19       29    2946.724    177.05243 2507       3285
8  20        3    3054.000     77.50484 2976       3131
9  21        8    2673.625     84.65887 2548       2765
10 23       15    2658.067    272.31034 2370       3034

In [106]:
df5.rand = sample_frac(df5, .5)
df5.rand

   city.mpg count mean.weight sd.weight min.weight max.weight
1  18        4    2994.500    126.54775 2824       3130
2  47        1    1488.000           NA 1488       1488
3  19       29    2946.724    177.05243 2507       3285
4  30        7    2001.429     78.25143 1890       2109
5  14        2    3807.500    130.81475 3715       3900
6  27       14    2372.071    225.50506 2209       3110
7  38        6    1916.167     91.16012 1837       2094
8  26       11    2325.455     92.72148 2120       2425
9  25        6    2401.500     97.43049 2293       2563
10 32        1    2145.000           NA 2145       2145
11 24       24    2535.583    295.33134 2128       3042
12 21        8    2673.625     84.65887 2548       2765